package com.markloy.markblog.mapper;

import com.markloy.markblog.pojo.Inform;
import com.markloy.markblog.pojo.InformExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    long countByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int deleteByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int insert(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int insertSelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    List<Inform> selectByExampleWithRowbounds(InformExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    List<Inform> selectByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    Inform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int updateByExample(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform
     *
     * @mbg.generated Wed Nov 25 19:58:20 CST 2020
     */
    int updateByPrimaryKey(Inform record);
}