package com.markloy.markblog.mapper;

import com.markloy.markblog.pojo.Visitor;
import com.markloy.markblog.pojo.VisitorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    long countByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int deleteByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int insert(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int insertSelective(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    List<Visitor> selectByExampleWithRowbounds(VisitorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    List<Visitor> selectByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    Visitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Visitor record, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int updateByExample(@Param("record") Visitor record, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int updateByPrimaryKeySelective(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Mon Nov 02 11:41:01 CST 2020
     */
    int updateByPrimaryKey(Visitor record);
}