#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #配置mapper.xml配置文件的位置
  mapper-locations: classpath:mapper/*.xml
  #配置别名包
  type-aliases-package: com.markloy.markblog.pojo

server:
  port: 8888
#logging:
#  level.com.markloy.markblog.mapper: debug
