# 端口配置
server:
  port: 8888

# spring配置
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.166.128:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # servlet配置
  servlet:
    # 上传文件大小设置
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT + 08

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #配置mapper.xml配置文件的位置
  mapper-locations: classpath:mapper/*.xml
  #配置别名包
  type-aliases-package: com.markloy.markblog.pojo

# OSS对象存储配置
aliyun:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accessKeyId: e0d074928cc27a4c6536f3052a4d54fe893d1b2c1e5dfb11d6746d169147a80e
  accessKeySecret: 65b52d47c2254847f3237ac1581cc018e64a318610beb9e55d25d2b603ee7067
  oss:
    bucketName: marker-fileupload
    filePatten: images/blog/dev/
    expiration: 31104000000

# 日志信息配置
logging:
  level:
    root: info
  file:
    name: logs/blog.log
    #单个日志文件保存100MB数据，超出则新建一个日志文件
    max-size: 10MB
    #日志文件保存15天
    max-history: 15



