package com.markloy.markblog.pojo;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.show_img
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private String showImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.admin_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.category_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tags_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private String tagsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.view_count
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.like_count
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gmt_create
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gmt_modified
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.context
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.show_img
     *
     * @return the value of article.show_img
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public String getShowImg() {
        return showImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.show_img
     *
     * @param showImg the value for article.show_img
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setShowImg(String showImg) {
        this.showImg = showImg == null ? null : showImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.admin_id
     *
     * @return the value of article.admin_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.admin_id
     *
     * @param adminId the value for article.admin_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.category_id
     *
     * @return the value of article.category_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.category_id
     *
     * @param categoryId the value for article.category_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tags_id
     *
     * @return the value of article.tags_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public String getTagsId() {
        return tagsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tags_id
     *
     * @param tagsId the value for article.tags_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setTagsId(String tagsId) {
        this.tagsId = tagsId == null ? null : tagsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.view_count
     *
     * @return the value of article.view_count
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.view_count
     *
     * @param viewCount the value for article.view_count
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.like_count
     *
     * @return the value of article.like_count
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.like_count
     *
     * @param likeCount the value for article.like_count
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gmt_create
     *
     * @return the value of article.gmt_create
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gmt_create
     *
     * @param gmtCreate the value for article.gmt_create
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gmt_modified
     *
     * @return the value of article.gmt_modified
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gmt_modified
     *
     * @param gmtModified the value for article.gmt_modified
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.context
     *
     * @return the value of article.context
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.context
     *
     * @param context the value for article.context
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}