package com.markloy.markblog.pojo;

public class Inform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.visitor_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer visitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.admin_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.article_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.message_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.type
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.state
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform.gmt_create
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.id
     *
     * @return the value of inform.id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.id
     *
     * @param id the value for inform.id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.visitor_id
     *
     * @return the value of inform.visitor_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.visitor_id
     *
     * @param visitorId the value for inform.visitor_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setVisitorId(Integer visitorId) {
        this.visitorId = visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.admin_id
     *
     * @return the value of inform.admin_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.admin_id
     *
     * @param adminId the value for inform.admin_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.article_id
     *
     * @return the value of inform.article_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.article_id
     *
     * @param articleId the value for inform.article_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.message_id
     *
     * @return the value of inform.message_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.message_id
     *
     * @param messageId the value for inform.message_id
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.type
     *
     * @return the value of inform.type
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.type
     *
     * @param type the value for inform.type
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.state
     *
     * @return the value of inform.state
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.state
     *
     * @param state the value for inform.state
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform.gmt_create
     *
     * @return the value of inform.gmt_create
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform.gmt_create
     *
     * @param gmtCreate the value for inform.gmt_create
     *
     * @mbg.generated Sun Nov 08 16:26:17 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}