package com.markloy.markblog.pojo;

public class VisitorLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorlike.id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorlike.visitor_id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    private Integer visitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorlike.article_id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorlike.gmt_create
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorlike.id
     *
     * @return the value of visitorlike.id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorlike.id
     *
     * @param id the value for visitorlike.id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorlike.visitor_id
     *
     * @return the value of visitorlike.visitor_id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public Integer getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorlike.visitor_id
     *
     * @param visitorId the value for visitorlike.visitor_id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public void setVisitorId(Integer visitorId) {
        this.visitorId = visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorlike.article_id
     *
     * @return the value of visitorlike.article_id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorlike.article_id
     *
     * @param articleId the value for visitorlike.article_id
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorlike.gmt_create
     *
     * @return the value of visitorlike.gmt_create
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorlike.gmt_create
     *
     * @param gmtCreate the value for visitorlike.gmt_create
     *
     * @mbg.generated Sat Nov 28 18:39:34 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}